# Generated by Django 2.2.5 on 2020-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200506_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
