# Generated by Django 2.2.5 on 2020-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200424_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
