# Generated by Django 2.2.5 on 2020-04-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200429_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomTyte',
            new_name='RoomType',
        ),
    ]
