# Generated by Django 2.2.5 on 2020-05-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200429_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(help_text='how many bedroom do you need?'),
        ),
    ]
