# Generated by Django 2.2.5 on 2020-04-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200428_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='patricipants',
            new_name='participants',
        ),
    ]
